stages:
  - lint

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

eslint:
  image: node:16.13.1-alpine
  stage: lint
  script:
    - npm install
    - npm run lint

prettier:
  image: node:16.13.1-alpine
  stage: lint
  script:
    - npm install
    - npm run check:format
