name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: node:16.13.1-alpine3.12
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint source code with ESLint
        run: npm run check:format

  prettier:
    runs-on: node:16.13.1-alpine3.12
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Prettier checker 
        run: npm run check:format
